#!/bin/sh
echo "Launching ElectrumX server..."
USERNAME=$(envdir ./env printenv USERNAME)
BITGESELLX=$(envdir ./env printenv BITGESELLX)
ulimit -n 4000 && exec 2>&1 envdir ./env envuidgid $USERNAME python3 $BITGESELLX
